name: Handle Remind Comments

on:
  issue_comment:
    types: [created]  

jobs:
  handle_remind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run roumusho action
        run: |
          python3 script/gen_task.py "${{ github.event.comment.body }}" "${{ github.event.issue.number }}"

      - name: Commit and push reminder file
        if: success()
        run: |
          git config --global user.name "roumusho"
          git config --global user.email "actions@github.com"
          git add reminds/tasks.json
          git commit -m "Add reminder for issue #${{ github.event.issue.number }}"
          git push origin HEAD:main 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
