name: Handle Remind Comments

on:
  issue_comment:
    types: [created]  

jobs:
  handle_remind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run roumusho action
        uses: abap34/roumusho@v0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          COMMENT_BODY: ${{ github.event.comment.body }}

      - name: Commit and push reminder file
        if: success()
        run: |
          git config --global user.name "roumusho"
          git config --global user.email "actions@github.com"
          git add reminder_*.txt
          git commit -m "Add reminder for issue #${{ github.event.issue.number }}"
          git push origin HEAD:main 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
