name: Handle Remind Comments

on:
  issue_comment:
    types: [created]  

jobs:
  handle_remind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Add task
        if: contains(github.event.comment.body, '/remind')
        run: |
          python3 script/add_task.py "${{ github.event.comment.body }}" "${{ github.event.issue.number }}"

      - name: Done task
        if: contains(github.event.comment.body, '/done')
        run: |
          python3 script/done_task.py "${{ github.event.comment.body }}" 
          gh issue comment ${{ github.event.issue.number }} --body "$(cat message.txt)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: $(cat message.txt)

      - name: Commit and push reminder file
        if: success()
        run: |
          git config --global user.name "roumusho"
          git config --global user.email "actions@github.com"
          git add reminds/tasks.json
          git commit -m "Add reminder for issue #${{ github.event.issue.number }}"
          git push origin HEAD:main 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
